apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prisma
  name: prisma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma
  template:
    metadata:
      labels:
        app: prisma
    spec:
      containers:
        - env:
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: prisma-configmap
                  key: PRISMA_CONFIG
          image: prismagraphql/prisma:1.34
          name: prisma
          ports:
            - containerPort: 4466
              protocol: TCP
      restartPolicy: Always
