apiVersion: v1
kind: Service
metadata:
  name: prisma
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: prisma-port
      port: 4466
      protocol: TCP
      targetPort: 4466
  selector:
    app: prisma
  type: NodePort
