--- # ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-blog-service
# spec:
#   storageClassName: ''
#   capacity:
#     storage: 10G
#   accessModes:
#     - ReadWriteOnce
#   gcePersistentDisk:
#     pdName: pd-blog-service
#     fsType: ext4
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-blog-service
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  # storageClassName: ''
  volumeName: pd-blog-service
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
